version: '3'
services:
  zookeeper:
    image: zookeeper:3.4.10
    restart: always
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888
  kafka:
    image: wurstmeister/kafka:0.10.2.0
    restart: always
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${INTERFACE_IP:-127.0.0.1}
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 0
      KAFKA_LOG_DIRS: /kafka/kafka-logs
  kafka-rest:
    image: confluentinc/cp-kafka-rest:3.2.1
    restart: always
    depends_on:
      - zookeeper
      - kafka
    ports:
      - 8082:8082
    environment:
       KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:2181
       KAFKA_REST_HOST_NAME: kafka-rest
  kafka-connect:
    image: gcr.io/wizzie-registry/wizzie-kc:0.0.1
    restart: always
    depends_on:
      - kafka
    ports:
      - 8083:8083
      - 5577:514/udp
      - 5576:601
    environment:
       CONNECT_BOOTSTRAP_SERVERS: kafka:9092
       CONNECT_GROUP_ID: prozzie-id
       CONNECT_CONFIG_STORAGE_TOPIC: __connect_config
       CONNECT_OFFSET_STORAGE_TOPIC: __connect_offset
       CONNECT_STATUS_STORAGE_TOPIC: __connect_status
       CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
       CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: "false"
       CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
       CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
       CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
       CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
       CONNECT_REST_ADVERTISED_HOST_NAME: ${INTERFACE_IP:-127.0.0.1}
  k2http:
    image: gcr.io/wizzie-registry/prozzie-k2http:1.3.0
    restart: always
    depends_on:
      - kafka
    environment:
      HTTP_POST_PARAMS: "apikey:${CLIENT_API_KEY}"
      KAFKA_OFFSET_RESET: "earliest"
      KAFKA_CONSUMER_GROUP: "k2http"
      KAFKA_BROKERS: "kafka:9092"
      HTTP_ENDPOINT: "${ZZ_HTTP_ENDPOINT:-http://localhost:8000/v1/data}"
      PIPELINE_QUEUE: 1000
      PIPELINE_BACKOFF: 10
      PIPELINE_RETRIES: 3
      LIMITER_MAX_MESSAGES: 5000
      LIMITER_MAX_BYTES: 0
      BATCH_WORKERS: 1
      BATCH_SIZE: 1000
      BATCH_TIMEOUT_MS: 100
      BATCH_DEFLASE: "false"
      HTTP_WORKERS: 1
      HTTP_INSECURE: "false"
      KAFKA_TOPICS: "*"
  f2k:
    image: gcr.io/wizzie-registry/prozzie-f2k:1.0.2
    restart: always
    depends_on:
      - kafka
    ports:
      - "${NETFLOW_COLLECTOR_PORT:-2055}:${NETFLOW_COLLECTOR_PORT:-2055}"
    environment:
      F2K_NTHREADS: 3
      KAFKA_TOPIC: "${NETFLOW_KAFKA_TOPIC:-flow}"
      COLLECTOR_PORT: "${NETFLOW_COLLECTOR_PORT:-2055}"
      NETFLOW_PROBES: "${NETFLOW_PROBES:-{\"sensors_networks\":{}}"
      RDKAFKA_QUEUE_BUFFERING_MAX_MS: 1000
  sfacctd:
    image: gcr.io/wizzie-registry/prozzie-sfacctd:1.6.2
    restart: always
    depends_on:
      - kafka
    ports:
      - "${SFLOW_COLLECTOR_PORT:-6343}:${SFLOW_COLLECTOR_PORT:-6343}"
    environment:
      KAFKA_BROKERS: "kafka"
      KAFKA_TOPIC: "${SFLOW_KAFKA_TOPIC:-flow}"
      COLLECTOR_PORT: "${SFLOW_COLLECTOR_PORT:-6343}"
      SFACCTD_RENORMALIZE: "${SFLOW_RENORMALIZE:-true}"
      AGGREGATE: "${SFLOW_AGGREGATE:-src_host}"
