version: '3'
services:
  zookeeper:
    image: zookeeper
    restart: always
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888
  kafka:
    image: wurstmeister/kafka:0.10.1.1
    restart: always
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${INTERFACE_IP:-127.0.0.1}
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 0
      KAFKA_LOG_DIRS: /kafka/kafka-logs 
  kafka-rest:
    image: gcr.io/wizzie-registry/prozzie-rest-proxy:3.2.1-1
    restart: always
    depends_on:
      - zookeeper
      - kafka 
    ports:
      - 8082:8082
    environment:
      KAFKAREST_HEAP_OPTS: -Xmx1g -Xms1g
  k2http:
    image: gcr.io/wizzie-registry/prozzie-k2http:latest
    restart: always
    depends_on:
      - kafka
    environment:
      PIPELINE_QUEUE: 1000
      PIPELINE_BACKOFF: 10
      PIPELINE_RETRIES: 3
      LIMITER_MAX_MESSAGES: 5000
      LIMITER_MAX_BYTES: 0
      BATCH_WORKERS: 1
      BATCH_SIZE: 1000
      BATCH_TIMEOUT_MS: 100
      BATCH_DEFLASE: "false"
      HTTP_WORKERS: 1
      HTTP_INSECURE: "false"
      KAFKA_TOPICS: "topic1 topic2"
